// Generates src/data/biblia-data.ts: a static map of every Bible JSON file so the
// data is bundled into the build instead of read from disk at runtime. This makes
// the package usable in the browser (no fs). Run via `yarn generate:data`.
import fs from 'fs';
import path from 'path';

const root = path.resolve(import.meta.dirname, '..');
const jsonDir = path.join(root, 'json');
const outFile = path.join(root, 'src', 'data', 'biblia-data.ts');

// macOS returns decomposed filenames from readdir (o + combining acute), while
// git stores them composed (o with acute as one code point). Without this
// normalization the generated file would carry whichever form the machine that
// ran the script happened to see, so regenerating on a Mac rewrote all 24
// accented import paths and broke the build on Linux. Normalize before sorting,
// because the two forms also sort differently.
const files = fs
  .readdirSync(jsonDir)
  .map((f) => f.normalize('NFC'))
  .filter((f) => f.endsWith('.json'))
  .sort();

const imports = files
  .map((f, i) => `import book${i} from '../../json/${f}';`)
  .join('\n');

const entries = files
  .map((f, i) => `  ${JSON.stringify(f.replace(/\.json$/, ''))}: book${i},`)
  .join('\n');

const out = `// AUTO-GENERATED by scripts/generate-data.mjs — do not edit by hand.
// Run \`yarn generate:data\` to regenerate after changing files in json/.
/* eslint-disable */
${imports}

export const BIBLIA_DATA: Record<string, unknown> = {
${entries}
};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, out);
console.log(`Wrote ${outFile} with ${files.length} JSON files.`);
