import { BibleBook } from "./types";

const bibleBooks: { old: BibleBook[]; new: BibleBook[] } = {
  old: [
    { abbreviation: "1Móz", name: "Mózes első könyve" },
    { abbreviation: "2Móz", name: "Mózes második könyve" },
    { abbreviation: "3Móz", name: "Mózes harmadik könyve" },
    { abbreviation: "4Móz", name: "Mózes negyedik könyve" },
    { abbreviation: "5Móz", name: "Mózes ötödik könyve" },
    { abbreviation: "Józs", name: "Józsué könyve" },
    { abbreviation: "Bír", name: "A bírák könyve" },
    { abbreviation: "Ruth", name: "Ruth könyve" },
    { abbreviation: "1Sám", name: "Sámuel első könyve" },
    { abbreviation: "2Sám", name: "Sámuel második könyve" },
    { abbreviation: "1Kir", name: "A királyok első könyve" },
    { abbreviation: "2Kir", name: "A királyok második könyve" },
    { abbreviation: "1Krón", name: "A krónikák első könyve" },
    { abbreviation: "2Krón", name: "A krónikák második könyve" },
    { abbreviation: "Ezsd", name: "Ezsdrás könyve" },
    { abbreviation: "Neh", name: "Nehémiás könyve" },
    { abbreviation: "Eszt", name: "Eszter könyve" },
    { abbreviation: "Jób", name: "Jób könyve" },
    { abbreviation: "Zsolt", name: "A Zsoltárok könyve" },
    { abbreviation: "Péld", name: "A példabeszédek könyve" },
    { abbreviation: "Préd", name: "A prédikátor könyve" },
    { abbreviation: "Énekek", name: "Énekek éneke" },
    { abbreviation: "Ézs", name: "Ézsaiás próféta könyve" },
    { abbreviation: "Jer", name: "Jeremiás próféta könyve" },
    { abbreviation: "JSir", name: "Jeremiás siralmai" },
    { abbreviation: "Ez", name: "Ezékiel próféta könyve" },
    { abbreviation: "Dán", name: "Dániel próféta könyve" },
    { abbreviation: "Hós", name: "Hóseás próféta könyve" },
    { abbreviation: "Jóel", name: "Jóel próféta könyve" },
    { abbreviation: "Ám", name: "Ámósz próféta könyve" },
    { abbreviation: "Abd", name: "Abdiás próféta könyve" },
    { abbreviation: "Jón", name: "Jónás próféta könyve" },
    { abbreviation: "Mik", name: "Mikeás próféta könyve" },
    { abbreviation: "Náh", name: "Náhum próféta könyve" },
    { abbreviation: "Hab", name: "Habakuk próféta könyve" },
    { abbreviation: "Zof", name: "Zofóniás próféta könyve" },
    { abbreviation: "Hag", name: "Haggeus próféta könyve" },
    { abbreviation: "Zak", name: "Zakariás próféta könyve" },
    { abbreviation: "Mal", name: "Malakiás próféta könyve" },
  ],
  new: [
    { abbreviation: "Mt", name: "Máté evangéliuma" },
    { abbreviation: "Mk", name: "Márk evangéliuma" },
    { abbreviation: "Lk", name: "Lukács evangéliuma" },
    { abbreviation: "Jn", name: "János evangéliuma" },
    { abbreviation: "ApCsel", name: "Az apostolok cselekedetei" },
    { abbreviation: "Róm", name: "Pál levele a rómaiakhoz" },
    { abbreviation: "1Kor", name: "Pál első levele a korinthusiakhoz" },
    { abbreviation: "2Kor", name: "Pál második levele a korinthusiakhoz" },
    { abbreviation: "Gal", name: "Pál levele a galatákhoz" },
    { abbreviation: "Ef", name: "Pál levele az efezusiakkoz" },
    { abbreviation: "Fil", name: "Pál levele a filippiekhez" },
    { abbreviation: "Kol", name: "Pál levele a kolosséiakhoz" },
    {
      abbreviation: "1Thessz",
      name: "Pál első levele a thesszalonikaiakhoz",
    },
    {
      abbreviation: "2Thessz",
      name: "Pál második levele a thesszalonikaiakhoz",
    },
    { abbreviation: "1Tim", name: "Pál első levele Timóteushoz" },
    { abbreviation: "2Tim", name: "Pál második levele Timóteushoz" },
    { abbreviation: "Tit", name: "Pál levele Tituszhoz" },
    { abbreviation: "Filem", name: "Pál levele Filemonhoz" },
    { abbreviation: "Zsid", name: "A zsidókhoz írt levél" },
    { abbreviation: "Jak", name: "Jakab levele" },
    { abbreviation: "1Pt", name: "Péter első levele" },
    { abbreviation: "2Pt", name: "Péter második levele" },
    { abbreviation: "1Jn", name: "János első levele" },
    { abbreviation: "2Jn", name: "János második levele" },
    { abbreviation: "3Jn", name: "János harmadik levele" },
    { abbreviation: "Júd", name: "Júdás levele" },
    { abbreviation: "Jel", name: "A jelenések könyve" },
  ],
};

export const getBibleBooks = (): BibleBook[] => [
  ...bibleBooks.old,
  ...bibleBooks.new,
];

export const getBibleBooksOldTestament = (): BibleBook[] => [...bibleBooks.old];

export const getBibleBooksNewTestament = (): BibleBook[] => [...bibleBooks.new];

export { bibleBooks };
