// AUTO-GENERATED by scripts/generate-data.mjs — do not edit by hand.
// Run `yarn generate:data` to regenerate after changing files in json/.
 
import book0 from '../../json/1Jn.json';
import book1 from '../../json/1Kir.json';
import book2 from '../../json/1Kor.json';
import book3 from '../../json/1Krón.json';
import book4 from '../../json/1Móz.json';
import book5 from '../../json/1Pt.json';
import book6 from '../../json/1Sám.json';
import book7 from '../../json/1Thessz.json';
import book8 from '../../json/1Tim.json';
import book9 from '../../json/2Jn.json';
import book10 from '../../json/2Kir.json';
import book11 from '../../json/2Kor.json';
import book12 from '../../json/2Krón.json';
import book13 from '../../json/2Móz.json';
import book14 from '../../json/2Pt.json';
import book15 from '../../json/2Sám.json';
import book16 from '../../json/2Thessz.json';
import book17 from '../../json/2Tim.json';
import book18 from '../../json/3Jn.json';
import book19 from '../../json/3Móz.json';
import book20 from '../../json/4Móz.json';
import book21 from '../../json/5Móz.json';
import book22 from '../../json/Abd.json';
import book23 from '../../json/ApCsel.json';
import book24 from '../../json/Bír.json';
import book25 from '../../json/Dán.json';
import book26 from '../../json/Ef.json';
import book27 from '../../json/Eszt.json';
import book28 from '../../json/Ez.json';
import book29 from '../../json/Ezsd.json';
import book30 from '../../json/Fil.json';
import book31 from '../../json/Filem.json';
import book32 from '../../json/Gal.json';
import book33 from '../../json/Hab.json';
import book34 from '../../json/Hag.json';
import book35 from '../../json/Hós.json';
import book36 from '../../json/JSir.json';
import book37 from '../../json/Jak.json';
import book38 from '../../json/Jel.json';
import book39 from '../../json/Jer.json';
import book40 from '../../json/Jn.json';
import book41 from '../../json/Jób.json';
import book42 from '../../json/Jóel.json';
import book43 from '../../json/Jón.json';
import book44 from '../../json/Józs.json';
import book45 from '../../json/Júd.json';
import book46 from '../../json/Kol.json';
import book47 from '../../json/Lk.json';
import book48 from '../../json/Mal.json';
import book49 from '../../json/Mik.json';
import book50 from '../../json/Mk.json';
import book51 from '../../json/Mt.json';
import book52 from '../../json/Neh.json';
import book53 from '../../json/Náh.json';
import book54 from '../../json/Préd.json';
import book55 from '../../json/Péld.json';
import book56 from '../../json/Ruth.json';
import book57 from '../../json/Róm.json';
import book58 from '../../json/Tit.json';
import book59 from '../../json/Zak.json';
import book60 from '../../json/Zof.json';
import book61 from '../../json/Zsid.json';
import book62 from '../../json/Zsolt.json';
import book63 from '../../json/biblia.json';
import book64 from '../../json/Ám.json';
import book65 from '../../json/Énekek.json';
import book66 from '../../json/Ézs.json';

export const BIBLIA_DATA: Record<string, unknown> = {
  "1Jn": book0,
  "1Kir": book1,
  "1Kor": book2,
  "1Krón": book3,
  "1Móz": book4,
  "1Pt": book5,
  "1Sám": book6,
  "1Thessz": book7,
  "1Tim": book8,
  "2Jn": book9,
  "2Kir": book10,
  "2Kor": book11,
  "2Krón": book12,
  "2Móz": book13,
  "2Pt": book14,
  "2Sám": book15,
  "2Thessz": book16,
  "2Tim": book17,
  "3Jn": book18,
  "3Móz": book19,
  "4Móz": book20,
  "5Móz": book21,
  "Abd": book22,
  "ApCsel": book23,
  "Bír": book24,
  "Dán": book25,
  "Ef": book26,
  "Eszt": book27,
  "Ez": book28,
  "Ezsd": book29,
  "Fil": book30,
  "Filem": book31,
  "Gal": book32,
  "Hab": book33,
  "Hag": book34,
  "Hós": book35,
  "JSir": book36,
  "Jak": book37,
  "Jel": book38,
  "Jer": book39,
  "Jn": book40,
  "Jób": book41,
  "Jóel": book42,
  "Jón": book43,
  "Józs": book44,
  "Júd": book45,
  "Kol": book46,
  "Lk": book47,
  "Mal": book48,
  "Mik": book49,
  "Mk": book50,
  "Mt": book51,
  "Neh": book52,
  "Náh": book53,
  "Préd": book54,
  "Péld": book55,
  "Ruth": book56,
  "Róm": book57,
  "Tit": book58,
  "Zak": book59,
  "Zof": book60,
  "Zsid": book61,
  "Zsolt": book62,
  "biblia": book63,
  "Ám": book64,
  "Énekek": book65,
  "Ézs": book66,
};
